CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    UUID,
    name    VARCHAR(255),
    email   VARCHAR(255),
    dob     DATE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID,
    title       VARCHAR(255),
    body        VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE,
    user_id   BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);